export const RESTORE_SPLASH = "RESTORE_SPLASH"
export const FETCH_START = "FETCH_START"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_ERROR = "FETCH_ERROR"
export const RESET = "RESET"
export const LOGIN_USER = "LOGIN_USER"
